config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :api, defaults: { format: "json" } do
    resources :categories, only: %i(update)
    resources :challenges, only: %i(show update) do
      scope module: :challenges do
        resources :runs, only: %i(create)
        resources :judges, only: %i(create)
      end
    end
  end
  resources :categories, except: %i(show) do
    resources :challenges, except: %i(index)
  end

  get "/login", to: "sessions#new"
  get "/auth/:provider/callback", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users, only: %i(destroy)

  root "categories#index"
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :challenges, dependent: :restrict_with_error

  include RankedModel
  ranks :row_order

  EDITOR_MODES = {
    Go: "ace/mode/golang",
    Java: "ace/mode/java",
    JavaScript: "ace/mode/javascript",
    PHP: "ace/mode/php",
    Perl: "ace/mode/perl",
    Python: "ace/mode/python",
    Ruby: "ace/mode/ruby"
  }

  validates :name, presence: true, uniqueness: true
  validates :docker_image, presence: true
  validates :editor_mode, inclusion: { in: EDITOR_MODES.values }
  validates :command, presence: true
  validates :extension, presence: true, format: { with: /\A[a-zA-Z]+\z/, message: "は英字のみ使えます" }
end

app/controllers/api/categories_controller.rb
# frozen_string_literal: true

class API::CategoriesController < API::BaseController
  before_action :authenticate_admin_for_api

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      head :created
    else
      render json: { messages: @category.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private
    def category_params
      params.require(:category).permit(:row_order_position)
    end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :authenticate_user
  before_action :authenticate_admin, except: :index
  before_action :set_category, only: %i(edit update destroy)

  def index
    @categories = Category.preload(:challenges).rank(:row_order).all
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    if @category.valid?
      begin
        Docker::Image.create('fromImage': @category.docker_image)
        if @category.save
          redirect_to root_path, notice: "カテゴリを登録しました。"
        else
          render :new, status: :unprocessable_entity
        end
      rescue
        flash.now[:alert] = "Docker imageの取得に失敗しました。"
        render :new
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @category.assign_attributes(category_params)

    if @category.valid?
      begin
        Docker::Image.create('fromImage': @category.docker_image)
        if @category.save
          redirect_to root_path, notice: "カテゴリを更新しました。"
        else
          render :new, status: :unprocessable_entity
        end
      rescue
        flash.now[:alert] = "Docker imageの取得に失敗しました。"
        render :edit
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @category.destroy
      redirect_to root_path, notice: "カテゴリを削除しました。"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :docker_image, :editor_mode, :command, :extension)
    end
end

app/views/categories/_form.html.slim
= form_for @category do |f|
  .columns.is-centered
    .column.is-6
      - if @category.errors.any?
        .notification.is-danger.is-light
          ul
            - @category.errors.full_messages.each do |message|
              li = message
      .field
        = f.label :name, class: "label"
        .control
          = f.text_field :name, class: "input", placeholder: "ruby"
      .columns
        .column
          .field
            = f.label :docker_image, class: "label"
            .control
              = f.text_field :docker_image, class: "input", placeholder: "ruby:3.0.2"
        .column
          .field
            = f.label :editor_mode, class: "label editor-mode-label"
            .control
              .select
                = f.select :editor_mode, options_for_select(Category::EDITOR_MODES, selected: @category.editor_mode)
      .field
        = f.label :command, "コード実行コマンド", class: "label"
        .command-field
          = f.text_field :command, class: "command-input", placeholder: "ruby", size: "7"
          span.command-input.ml-2 code.
          = f.text_field :extension, class: "command-input", placeholder: "rb", size: "5"
      .field
        .control
          = f.submit class: "button is-primary is-fullwidth"

app/views/categories/edit.html.slim
section.section
  .container
    h1.title.is-3.has-text-centered.mb-3
      = @category.name
    = render "form"
    .columns.is-centered.mt-2
      .column.is-6.is-flex.is-justify-content-space-between
        = link_to "もどる", root_path, class: "is-size-7"
        = link_to 'カテゴリを削除する', @category, data: { confirm: '本当に削除しますか？' }, method: :delete, class: "has-text-grey-light is-size-7"

app/views/categories/index.html.slim
section.section
  .container
    h1.challenges.title.is-4.mb-5
      | プログラミングテスト一覧
    .columns.is-multiline.is-variable.is-6.js-sortable data-model="categories"
      - @categories.each do |category|
        - challenge_count = category.challenges.size
        - archivement_count = category.challenges.select{ |c| c.has_archivement?(current_user) }.size
        .column.is-4.item data-id="#{category.id}"
          .category
            .header class="#{"handle" if current_user.admin}"
              h3.name = category.name
              .status.is-size-7
                = "#{archivement_count}/#{challenge_count}"
                progress.progress.is-success.is-small value="#{archivement_count}" max="#{challenge_count}"
            .body
              ul.challenges.js-sortable data-model="challenges"
                - category.challenges.rank(:row_order).each do |challenge|
                  li.item data-id="#{challenge.id}"
                    = link_to category_challenge_path(category, challenge), class: "link" do
                      - if challenge.has_archivement?(current_user)
                        i.fas.fa-check.is-size-7.has-text-success.mr-2
                      - else
                        i.fas.fa-minus.is-size-7.has-text-grey-lighter.mr-2
                      span.challenge-title
                        = challenge.title
                    - if current_user.admin
                      .buttons
                        button.button.is-light.is-small.handle
                          span.icon.is-small
                            i.fas.fa-arrows-alt-v
                        = link_to edit_category_challenge_path(category, challenge), class: "button is-small edit" do
                          i.fas.fa-pen
              - if current_user.admin
                .new-challenge
                  = link_to new_category_challenge_path(category), class: "button is-small has-background-white mr-1" do
                    i.fas.fa-plus-circle.mr-1
                    | 問題を追加する
                  - if current_user.admin
                    = link_to edit_category_path(category), class: "button is-small has-background-white" do
                      i.fas.fa-pen
      - if current_user.admin
        .column.is-4
          = link_to new_category_path, class: "new-category" do
            i.fas.fa-plus-circle.mr-1
            | カテゴリを追加する

app/views/categories/new.html.slim
section.section
  .container
    h1.title.is-3.has-text-centered.mb-3
      | 新規カテゴリ
    = render "form"
    .columns.is-centered.mt-2
      .column.is-6.is-flex.is-justify-content-space-between
        = link_to "もどる", root_path, class: "is-size-7"